import pandas as pd
import numpy as np
import xgboost as xgb
import onnxmltools
from onnxmltools.convert.common.data_types import FloatTensorType
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score

# 1. Load the data generated by backtester_2.js
print("📊 Loading training data...")
df = pd.read_csv('training_jupiter_5m.csv')

# Drop any rows with missing values if they slipped through
df.dropna(inplace=True)

# 2. Separate Features (X) and Target Label (y)
# CRITICAL FIX: Extract and sort ONLY the 6 features used by production inference
feature_order = [
    'directionIntent', 'rsi', 'rvol', 'atrPercentage', 'prevADX', 'bodySize'
]
X = df[feature_order]
y = df['target_win']

print(f"✅ Dataset loaded. Total samples: {len(df)} | Wins: {sum(y == 1)} | Losses: {sum(y == 0)}")

# 3. Stratified Train-Test Split (preserves win/loss ratio in both sets)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# 4. Handle Class Imbalance dynamically
scale_pos_weight = (len(y_train) - sum(y_train)) / sum(y_train)

# 5. Initialize and Train the XGBoost Classifier
print("🤖 Training XGBoost Veto Engine...")
model = xgb.XGBClassifier(
    objective='binary:logistic',
    n_estimators=150,
    learning_rate=0.05,
    max_depth=7,              # Kept shallow to prevent overfitting on noisy market data
    subsample=0.8,            # Use 80% of rows per tree to add robustness
    colsample_bytree=0.8,     # Use 80% of features per tree
    scale_pos_weight=scale_pos_weight,
    random_state=42
)


model.fit(X_train.values, y_train.values)


# 6. Evaluate Performance
preds = model.predict(X_test)
probs = model.predict_proba(X_test)[:, 1] # Probability of a win

print("\n=== 📈 MODEL EVALUATION ===")
print(f"Accuracy Score: {accuracy_score(y_test, preds):.4f}")
print("\nClassification Report:")
print(classification_report(y_test, preds, target_names=['Loss', 'Win']))

# 7. Extract Feature Importance
print("\n=== 💡 FEATURE IMPORTANCE ===")
importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': model.feature_importances_
}).sort_values(by='Importance', ascending=False)
print(importance.to_string(index=False))

# 8. Save the Model to ONNX Format
# CRITICAL FIX: Convert and save as .onnx to match production engine expectations
print("\n💾 Saving model to ONNX...")
initial_types = [('input', FloatTensorType([None, X.shape[1]]))]
onnx_model = onnxmltools.convert_xgboost(model, initial_types=initial_types)

with open("veto_engine.onnx", "wb") as f:
    f.write(onnx_model.SerializeToString())
    
print("✅ Done! Saved as 'veto_engine.onnx'")
